[main]
font=hack


icon-theme=Papirus-Dark
icons-enabled=true


prompt=" "


horizontal-pad=20
vertical-pad=14
inner-pad=10

# Высота строки 
line-height=30

# Количество  строк 
lines=9

# Ширина окна в символах
width=85

[colors]
background=161821ff

text=c6c8d1ff

match=8ab4f8ff

selection=8ab4f8ff

selection-text=161821ff

selection-match=161821ff

border=2a2d3aff

[border]
width=1
radius=0

[dmenu]
exit-immediately-if-empty=true
