[general]


# ===WINDOW===
[window]
padding = {
	x = 20,
	y = 10
}
decorations = "None" #cuz tiling




# ===FONT===
[font]
size = 12
offset = {
	x = 0,
	y = 0
}

normal = {
	family = "hack",
	style = "regular"
}

bold = {
	family = "hack",
	style = "bold"
}

italic = {
	family = "hack",
	style = "italic"
}

[scrolling]
history = 15000
multiplier = 5


# ===COLORS===
[colors.primary]
foreground = "#fff9e8"
background = "#040904"


[colors.normal]
black   = "#0B1E33"
red     = "#b34a33"
green   = "#4A7C6F"
yellow  = "#D9A876"
blue    = "#169400"
magenta = "#17b580"
cyan    = "#7bcf63"
white   = "#E8D9C0"
 
[colors.bright]
black   = "#4f4f4f"
red     = "#C46B4F"
green   = "#6FA89A"
yellow  = "#F0C896"
blue    = "#2e7920"
magenta = "#234413"
cyan    = "#529e2c"
white   = "#F5EBD8"


[mouse]
hide_when_typing = true

